### ISSUE TITLE
Issue Template

### ISSUE THREAD

**Issue by intel-aero** [intel-aero/meta-intel-aero#1]
**Issue Template:**

**Issue Type:** _It can be Bug, Task, Feature, Risk, Story_

**Summary:** _A short summary to explain the issue in one or two lines_

**Description:** _Add details of the issue such as, expected behavior, current behavior, how often its reproduced, steps to reproduce etc_

**Component affected:** _Such as USB, wifi, etc_

**Git tag tested:** _Example: v01.00.01_

**BIOS Version:** _Exmaple: Aero-01.00.03_

_Note: Attach logs, validation reports, test cases or any other issue related documents_

**Comment by lucasdemarchi** [comment]
This should be in a .github directory.
