### ISSUE TITLE
include the latest bios's .rpm file on the .iso

### ISSUE THREAD

**Issue by rmackay9** [intel-aero/meta-intel-aero#104]
In the current instructions, the user must download the BIOS's .rpm file and the install it:
https://github.com/intel-aero/meta-intel-aero/wiki/02-Initial-setup#flashing-the-bios

This step could be greatly simplified if the .rpm file was included in the .iso image.  Then the user could at least skip the copy-to-the-vehicle part of it which is actually the most difficult part.  The .rpm file is not so big either so it should fit easily in the .iso.

**Comment by lucasdemarchi** [comment]
In the next version it will be very easy to copy a file to the board, so we don't need to add the bios there.
