### ISSUE TITLE
wiki: slightly re-order the 02-Initial-setup wiki instructions's Flashing section

### ISSUE THREAD

**Issue by rmackay9** [intel-aero/meta-intel-aero#105]
The 02-initial-setup wiki page could be more clear by doing this:

- after the "To summarize:....4. .px4 for Flight controller" lines, start the "Flashing the BIOS" section.
- the lines from "Go to download.." to "On windows, open Win32 Disk Imager and check.." should be moved to the "Flashing Intel Aero Linux Distribution" section.
- the "Change to Wifi client to have internet access" is not really part of "Flashing" so we should either add a new title (i.e. "Wifi Setup") or make the "Change to Wifi.." the same font as "Flashing"

**Comment by guermonprez** [comment]
I clarified the structure: what is needed, then flashing each part of the RTF, then a foot note about the next steps including a link to the wifi. wifi is not part of a new sysadmin page.
