### ISSUE TITLE
wiki: flashing-the-bios should say how to get the .rpm file on the vehicle

### ISSUE THREAD

**Issue by rmackay9** [intel-aero/meta-intel-aero#106]
Ahead of this other enhancements being completed (https://github.com/intel-aero/meta-intel-aero/issues/104), it would be nice to give more specific instructions on where to download the .rpm file from and how to copy it to the vehicle in the "flashing the bios" section (https://github.com/intel-aero/meta-intel-aero/wiki/02-Initial-setup#flashing-the-bios).

To be more specific:

- under "Flashing the BIOS" the first instruction should "Go to the downloadcenter.intel.com page to download the Capsule/BIOS" file".
- "Copy the .rpm file to the board" should specify exactly how to get the file to the vehicle.  If it's "ssh" then the exact ssh command.  For the USB drive method it should include the same stuff from the "Flash Intel Aero linux distribbtion" section about mounting the SD card.

**Comment by guermonprez** [comment]
hello

indeed. I clarified the download instructions and the usb mounting commands.
download : "Where to get the files: downloadcenter.intel.com page to download the .rpm UEFI-BIOS file and .iso linux image."

flash : "Get an empty USB thumb drive, format it as FAT32 from your workstation and copy the rpm file you got from the download center (link) on it.
Plug it on aero and type the following commands for the installation:
sh-4.3# mount /dev/sda1 /mnt # we mount the drive
sh-4.3# rpm -ivh /mnt/capsule*.rpm # install rpm
sh-4.3# reboot"

for scp, I consider that if people are interested in scp, they'll know how to do it on their system.
