### ISSUE TITLE
wiki: add "ArduPilot" along side "px4"

### ISSUE THREAD

**Issue by rmackay9** [intel-aero/meta-intel-aero#108]
ArduPilot should be added alongside "px4" in a few places on the [02-Initial-setup](https://github.com/intel-aero/meta-intel-aero/wiki/02-Initial-setup) page:

- "if you do PX4 development" should become "if you do PX4 or ArduPilot development"
- "px4 for the Flight Controller" should become "px4 or ArduPilot for the Flight Controller"
- "Instructions for flashing ArduPilot" are going to be provided soon" can now be replaced with "Instructions for flashing ArduPilot can be found [here](http://ardupilot.org/copter/docs/common-intel-aero-rtf.html)"
- we need a whole new page equivalent to the "Update PX4 Firmware (only for Aero Ready to Fly Drone)

**Comment by guermonprez** [comment]
hello

For now, px4 is supported and provided by intel in the official release so I would not present both as equal choices in the doc.
I added ardupilot as a note after px4 mention and as an ecosystem partner. "(By default Intel is proposing and supporting px4 on Aero Flight Controller, but ArduPilot.org has documented the flashing procedure for ArduPilot)."

Randy: for your page. the password for the wifi is 1234567890 and not 123456789 I think.
If you'd like to propose a longer, better description/video of what ardupilot can do on aero, feel free to share with me. We can add it to the aero ecosystem page, or have a ecosystem page for ardupilot if it's long enough.

thanks
