### ISSUE TITLE
scripts: add launcher script for gstreamer-QGroundControl

### ISSUE THREAD

**Issue by guermonprez** [intel-aero/meta-intel-aero#109]
While we wait for a future multi streaming solution,
we could include a script in the image for the gtreamer-qgroundcontrol
command (it is part of the typical drone demo):

gst-launch-1.0 v4l2src  device=/dev/video13 do-timestamp=true \
    ! video/x-raw, format=YUY2, width=640, height=480, framerate=15/1 \
    ! autovideoconvert ! vaapih264enc ! rtph264pay \
    ! udpsink host=192.168.8.2 port=5600

**Comment by lucasdemarchi** [comment]
> While we wait for a future multi streaming solution,

That's around the corner so I don't want to add it just for being removed before a release. If for next release (v1.4 since v1.3 is already "closed") for some reason camera-streaming is not merged, we can add one.
