### ISSUE TITLE
Bitbake with meta-intel-aero-1.2 fails: DISTRO poky-aero not found

### ISSUE THREAD

**Issue by majassow** [intel-aero/meta-intel-aero#114]
I've downloaded and unpacked the meta-intel-aero-1.2 content into my poky directory and now bitbake complains that the OE-core sanity checker detected a misconfiguration....DISTRO 'poky-aero' not found.

I note that the original local.conf references just 'poky' not 'poky-aero'.

Are there other changes I need to make other than just unpacking the new meta-intel-aero recipes into the poky directory?

**Comment by lucasdemarchi** [comment]
You should be using the manifest to control what layers are enabled.

**Comment by lucasdemarchi** [comment]
https://github.com/intel-aero/meta-intel-aero/issues/111#issuecomment-294635619 has the commands.
