### ISSUE TITLE
Update modem-enable to use to rc-update

### ISSUE THREAD

**Issue by avinash-palleti** [intel-aero/meta-intel-aero#118]
recipes-support/modem-enable/modem-enable.bb recipe file has below lines,

    install -d ${D}${sysconfdir}/init.d/
    install -d ${D}${sysconfdir}/rc0.d/
    install -d ${D}${sysconfdir}/rc1.d/
    install -d ${D}${sysconfdir}/rc2.d/
    install -d ${D}${sysconfdir}/rc3.d/
    install -d ${D}${sysconfdir}/rc4.d/
    install -d ${D}${sysconfdir}/rc5.d/
    install -d ${D}${sysconfdir}/rc6.d/
    install -m 0755 ${WORKDIR}/modem-enable ${D}${sysconfdir}/init.d/
    ln -sf ../init.d/modem-enable      ${D}${sysconfdir}/rc0.d/K20modem-enable
    ln -sf ../init.d/modem-enable      ${D}${sysconfdir}/rc1.d/K20modem-enable
    ln -sf ../init.d/modem-enable      ${D}${sysconfdir}/rc2.d/S20modem-enable
    ln -sf ../init.d/modem-enable      ${D}${sysconfdir}/rc3.d/S20modem-enable
    ln -sf ../init.d/modem-enable      ${D}${sysconfdir}/rc4.d/S20modem-enable
    ln -sf ../init.d/modem-enable      ${D}${sysconfdir}/rc5.d/S20modem-enable
    ln -sf ../init.d/modem-enable      ${D}${sysconfdir}/rc6.d/k20modem-enable

Need to update this to use rc-update

**Comment by avinash-palleti** [comment]
See: http://www.yoctoproject.org/docs/1.8/ref-manual/ref-manual.html#var-INITSCRIPT_PARAMS and http://www.yoctoproject.org/docs/1.8/ref-manual/ref-manual.html#var-INITSCRIPT_NAME and http://www.yoctoproject.org/docs/1.8/ref-manual/ref-manual.html#ref-classes-update-rc.d

**Comment by whbruce** [comment]
A couple of things
1. This seems at odds with moving to systemd (#115)
2. Refer to appropriate version of documentation (i.e. 2.1)

**Comment by avinash-palleti** [comment]
@lucasdemarchi 
Shall we move this temporarily to use update-rc until we migrate to systemd ?

**Comment by lucasdemarchi** [comment]
@whbruce this is a small change that will help with the systemd (init files won't be installed when choosing systemd as the init).  If we can go to systemd without having this as an intermediary step, I'm fine skipping it.

**Comment by whbruce** [comment]
Understood. Stick with your plan.
