### ISSUE TITLE
wifi connection & BIOS update

### ISSUE THREAD

**Issue by sungwunyang** [intel-aero/meta-intel-aero#12]
hi 
I bought an Aero board this time. There is a problem trying to connect wifi before basic test.
When switching from AP mode to station mode, the program continues to repeat as if it had an infinite loop.
When you exit the mode, wlan0 disappears. In this case, wlan0 appears in the format.
In addition, iwconfig does not hold all drives.
Also, after updating the BIOS, the board suddenly goes on fire, and then it dies and can not even format it.
Please let me know what the reason is.

**Comment by intel-aero** [comment]
Hi - Please update to latest Software Release and try your test again. Please follow below link: https://github.com/intel-aero/meta-intel-aero/wiki/Upgrade-To-Latest-Software-Release
