### ISSUE TITLE
Power down issues in Aero RTF using latest update

### ISSUE THREAD

**Issue by turnersr** [intel-aero/meta-intel-aero#122]
Hello,

I updated the RTF drone using [CI build](http://ec2-52-59-242-235.eu-central-1.compute.amazonaws.com:8080/job/aero-build-master/lastSuccessfulBuild/artifact/poky/build/tmp/deploy/images/intel-aero/intel-aero-image-intel-aero-20170420164020.iso) . When I go to turn off the drone using the power button nothing happens. 

I expect that I would see some indication that shutdown is occurring, but when I push and hold the power button nothing happens. 

When I type `shutdown now` in the terminal the drone does try to shutoff. However,when drone tries turn off  it keeps printing information related to "serial8250". 

Please the attached image for what happens after I type `shutdown now`
![20170420_135219](https://cloud.githubusercontent.com/assets/743360/25244979/d498de48-25d0-11e7-92b1-9ca692f50da3.jpg)

Thank you.

**Comment by lucasdemarchi** [comment]
> I updated the RTF drone using CI build . When I go to turn off the drone using the power button nothing happens.

Were you able to successfully updated or does this happen with the updated version?

**Comment by turnersr** [comment]
I successfully updated and even got some code to run that uses the depth camera. I was able to see the results through my attached monitor.

**Comment by lucasdemarchi** [comment]
There's nothing I can see here that would handle the power switch. Did you also update the bios? I think this is handled there rather than on the OS level. I'll take a look on it.

**Comment by lucasdemarchi** [comment]
Ok, found it.  The  power down request does come via bios, but we are not handling it correctly on v1.3. We were on v1.2. I'll fix it today. Thanks.
