### ISSUE TITLE
Broken link on calibration procedures

### ISSUE THREAD

**Issue by cnpcshangbo** [intel-aero/meta-intel-aero#125]
The [QGroundControl](https://github.com/meta-intel-aero/wiki/03-First-flight#qgroundcontrol) link on page 
https://github.com/intel-aero/meta-intel-aero/wiki/02-Initial-setup#flashing-the-flight-controller-rtf-only
doesn't exist anymore.

**Comment by lucasdemarchi** [comment]
Fixed, thanks.
