### ISSUE TITLE
Older Version instead of 1.3.1 on the download page

### ISSUE THREAD

**Issue by toashwin** [intel-aero/meta-intel-aero#131]
Hi 
Observing 3 issues on the 1.3.1 download page: 

Issue 1) 
When I try to download the latest ISO.. I am getting Version 1.00.4 instead of 1.3.1. 
The page I was download is: 
https://downloadcenter.intel.com/download/26748/Intel-Aero-Platform-for-UAVs-Installation-Files?v=t

The md5sum expected is: 
9623a8f81a81687b41038b677eaddd7c
But I get: 
7cdb1fb4ac945e204c9ba85eaac1c9fb   

Issue 2) I see that the date at the top still shows 11/1/2016
Issue 3) On the left side panel. it has link to only .iso file. It does not have links to the kernal and Capsule.

Thanks
Ashwin

**Comment by lfelipe** [comment]
Thanks for reporting this, there was a leftover link that had not been updated (but the download button on the left already had the correct one).

Correct link is: https://downloadmirror.intel.com/26748/eng/intel-aero-image-intel-aero.iso

This has now been fixed on download center.
