### ISSUE TITLE
Custom Firmware: How to increase streaming rate?

### ISSUE THREAD

**Issue by icoderaven** [intel-aero/meta-intel-aero#132]
Hi

So I finally got around to compiling my own firmware from master and flashing it on to the STM32. However, my usual hack of changing the streaming rate in src/modules/mavlink_main.cpp is not having the desired effect (e.g. I can only push the HIGHRES_IMU stream to ~30Hz), and nor is trying to change the mavlink start command in the rcS helping.

Is there a config file that overrides the mavlink start command settings for the aero that are present in rcS?

Thanks for the help!

**Comment by lucasdemarchi** [comment]
@icoderaven I guess this is more a question to the PX4/Firmware repository. In `ROMFS/px4fmu_common/init.d/rcS` you can see what's the limit for the 460800 baud rate:

```
                if param compare SYS_COMPANION 460800                                                                                        
                then                                                                                                                         
                        mavlink start -d ${MAVLINK_COMPANION_DEVICE} -b 460800 -m onboard -r 5000 -x                                         
                fi                                                                             ```
```

Due to the logger using a lot of the bandwidth, it is more limited for the other things.

But as I said, let's discuss this on PX4/Firmware rather than here.
