### ISSUE TITLE
How to capture image using VGA and 8M Camera?

### ISSUE THREAD

**Issue by toashwin** [intel-aero/meta-intel-aero#136]
I was going over the article at: 
   https://communities.intel.com/thread/112209
But on my aero drone, I dont have "capture_example" command. so Could not execute following command. 
  sh-4.3# C=10 INPUT=0 MODE=PREVIEW capture_example --userp -d /dev/video0 

I am using the latest image. version "1.3.1" obtained from:  
   https://downloadcenter.intel.com/download/26748/Intel-Aero-Platform-for-UAVs-Installation-Files?v=t

Thanks
Ash

**Comment by lfelipe** [comment]
@toashwin that capture_example listed was posted on another topic in the community here: https://communities.intel.com/thread/110654

The source code for that can be found here: https://github.com/intel-aero/sample-apps

That example is not distributed inside the release though, so thats why you could not find it there.
