### ISSUE TITLE
How do I connect a LidarLite v3 to the Aero?

### ISSUE THREAD

**Issue by icoderaven** [intel-aero/meta-intel-aero#139]
There are a lot of confusing instructions available - and this is in a grey area between the PX4 firmware and the aero hardware. I tried following the pinout on https://dev.px4.io/en/flight_controller/intel_aero.html but that doesn't work for me. Then @lucasdemarchi asked me about the PR https://github.com/PX4/Firmware/pull/7070 and that also seemed to suggest that I had to update the FPGA firmware in order to use the new bus opened on the telemetry port. I haven't tried it, but a little bit of clarity would be very much appreciated! This is the last thing that stands between me being able to use this platform for most of my research purposes! (And figuring out how to use it with QGroundControl, but that should be easy with mavros fixed now.)

**Comment by lucasdemarchi** [comment]
@icoderaven we are waiting PX4 v1.6 get out in order to apply that PR since it also needs the update fpga firmware (https://github.com/intel-aero/intel-aero-fpga/pull/2 - mind you this is the *source* code of the fpga... you would need to compile it in quartus in order to be able to test).
