### ISSUE TITLE
boot complete notification with RGB led is broken

### ISSUE THREAD

**Issue by lucasdemarchi** [intel-aero/meta-intel-aero#146]

**Comment by lucasdemarchi** [comment]
need to add proper systemd service

**Comment by avinash-palleti** [comment]
init_start.sh and init_complete.sh which are under meta-intel-aero-base/recipes-core/initscripts/ have to be started by a systemd service right ?

**Comment by vidhyagithub** [comment]
Placing above scripts (init_start.sh & init_complete.sh) across the desired run levels of INIT (/etc/rcx.d) might solve this issue. Also it has to be noted that reboot&update script (meta-intel-aero-base/recipes-support/scripts/files/aero-reboot-update.py) too controls LED pattern during reboot&update.

**Comment by avinash-palleti** [comment]
@vidhyagithub INIT scripts will not work as we moved to systemd

**Comment by Rjasuja** [comment]
@lucasdemarchi i have added the service files for init_start and init_complete in this patch : https://github.com/Rjasuja/meta-intel-aero-base/commit/e9de27d1dc23f6d8a1f348bf3b308e0cc9a16f01
Please review
