### ISSUE TITLE
Reevaluate eee-acpi-scripts

### ISSUE THREAD

**Issue by anselmolsm** [intel-aero/meta-intel-aero#178]
This issue is to remind us to continue https://github.com/intel-aero/meta-intel-aero-base/pull/9 in future.

**Comment by padmashree9110** [comment]
@anselmolsm I have seen IRC chat and verified Power on/off with button before submitting PR.(forgot to add a note)
Is there anything else that I need to verify.

**Comment by anselmolsm** [comment]
@lucasdemarchi raised the concern that the soft shutdown is not working properly in 1.4.
@avinash-palleti, could you please share your findings about it?  Thanks.

**Comment by anselmolsm** [comment]
Thanks @avinash-palleti . With regards to the evaluation, I think it's done. If we identify there's a problem with the shutdown, we'll report a new issue to track that as a bug.
