### ISSUE TITLE
Not rebooting after aerofc-update.fc

### ISSUE THREAD

**Issue by guermonprez** [intel-aero/meta-intel-aero#180]
hello

the fc update is working well, and ends with "rebooting"
but it's not rebooting, I'm still on the shell.
1.4.0-dev

thanks, paul

**Comment by lucasdemarchi** [comment]
What do you mean by "I'm still on the shell"? What reboots is aerofc, not aero (where the shell is running)

**Comment by guermonprez** [comment]
ok my mistake then. should be good. thanks
