### ISSUE TITLE
mavlink examples: waiting heartbeat for ever

### ISSUE THREAD

**Issue by guermonprez** [intel-aero/meta-intel-aero#181]
git clone https://github.com/01org/mavlink-router.git
cd mavlink-router
python examples/heartbeat-print.py  127.0.0.1:5760

is waiting for ever for "mav.wait_heartbeat()", not printing the beats

But:
1. if I write a code without the wait and a sleep of 1sec,
it works (I can do things like arm motors)
2. telnet 127.0.0.1 5760 shows constant messages

thanks

**Comment by lucasdemarchi** [comment]
This is the udp example and you are trying a TCP port

**Comment by guermonprez** [comment]
indeed, thanks
