### ISSUE TITLE
SPI in PCI mode

### ISSUE THREAD

**Issue by ohshout** [intel-aero/meta-intel-aero#184]
Hello,

A quick question: is there any way to set SPI devs to PCI mode. The option seems to be grayed out in BIOS. Any reason why?

Thanks a lot!
Tom.

**Comment by lucasdemarchi** [comment]
As of now, we don't have it supported.  It would need a bios change request and check it works ok on Linux. I can't give you any estimate of this happening, but it's noted down as something to look at.
