### ISSUE TITLE
Enable watchdog functionality in Intel-Aero platforms

### ISSUE THREAD

**Issue by vjayara1** [intel-aero/meta-intel-aero#2]
Issue Type: Feature/Enhancement

Summary: Enable Watchdog functionality

Description: This patch aims to enable watchdog capability for the intel-aero platform, so that if the kernel/platform hangs by any chance the platform will be rebooted automatically after the TIMEOUT period.

Component: system feature

BIOS version: 01.00.05

**Comment by vjayara1** [comment]
This issue will be addressed within the next couple of releases

**Comment by icpda** [comment]
Please keep open till the commit that address the issue is publish and close mentioning the commit id

**Comment by intel-aero** [comment]
Feature is enabled in release v01.00.02.
