### ISSUE TITLE
cockpit plugin: Network

### ISSUE THREAD

**Issue by anselmolsm** [intel-aero/meta-intel-aero#200]
Add a network plugin that interacts with the network management software (connman):
 - [ ] 1)  AP setup: Change SSID and password
 - [ ] 2)  Factory reset - restores the default wifi settings (SSID and password)

**Comment by Rjasuja** [comment]
Submitted PR: https://github.com/intel-aero/aero-cockpit-plugins/pull/2

**Comment by Rjasuja** [comment]
Attaching sample screenshots for the plugin:

![network](https://user-images.githubusercontent.com/25738737/28213264-f5c7ab28-68c2-11e7-8897-f0a0149837b2.JPG)
![change_ssid](https://user-images.githubusercontent.com/25738737/28213265-f5ce59f0-68c2-11e7-8c28-bf17fc9ca360.JPG)
![reset_ssid](https://user-images.githubusercontent.com/25738737/28213266-f5d1e5ca-68c2-11e7-9a33-10a9c77a2f16.JPG)

**Comment by avinash-palleti** [comment]
PR merged https://github.com/intel-aero/aero-cockpit-plugins/pull/5
