### ISSUE TITLE
cockpit plugin: docker plugin

### ISSUE THREAD

**Issue by anselmolsm** [intel-aero/meta-intel-aero#203]
Evaluate the existing cockpit docker plugin and provide feedback, then a decision can be made if additional features are required.

**Comment by Rjasuja** [comment]
Docker support in Cockpit includes : 
1. Getting New Images
2. Starting Docker server
3. Starting different containers(with different environment variables) from the same image
4. Manages Resources
5. Manages Container Resources.

Tried Downloading Ros container and launching roscore. It worked. Attaching screenshots.

Docker Statistics : 
![docker_statistics](https://user-images.githubusercontent.com/25738737/28265006-43ee2526-6b0b-11e7-9eac-6d4132b67898.png)
Running Container: 
![running_container](https://user-images.githubusercontent.com/25738737/28265017-4ee95d9c-6b0b-11e7-9aae-51c95f98873d.png)
Resource Limits of docker : 
![resource_limits_runnign_docker](https://user-images.githubusercontent.com/25738737/28265023-589baf0c-6b0b-11e7-9549-3320dbd98bf0.png)
Roscore launched : 
![resource_container](https://user-images.githubusercontent.com/25738737/28265043-70eac80e-6b0b-11e7-9de9-383b1fa2ca0f.png)

**Comment by lucasdemarchi** [comment]
Nice. Please send a PR enabling it back. Thanks.

**Comment by Rjasuja** [comment]
Docker is enabled by default.

**Comment by lucasdemarchi** [comment]
Oh, great! That means I didn't remove it... Checking https://github.com/intel-aero/meta-intel-aero/commit/73ebb0f49379b8f9c735f71362fc2a3861c3fe5a, indeed I didn't.

thanks for testing, it was good to have this nonetheless since we can use your tests to add image to the documentation later :)
