### ISSUE TITLE
cockpit plugin: Software Update - check SDK updates

### ISSUE THREAD

**Issue by anitha-suresh** [intel-aero/meta-intel-aero#208]

**Comment by anselmolsm** [comment]
This is a step after #202

**Comment by lfelipe** [comment]
@anitha-suresh is this about providing information on updates to the Yocto SDK? Not sure whether cockpit would be a good location for that. Can you provide more description

**Comment by anitha-suresh** [comment]
@lfelipe, I meant about the SDK which is built along with the Yocto image and hence I had mentioned that in the title (original title) . This would be beneficial to the app developers in getting latest SDK.

**Comment by anitha-suresh** [comment]
As cockpit runs on the board, giving the option of Yocto SDK might not make much sense I guess. Maybe we need to figure out another way to help the app developer in sharing the link to update SDK and host it separately?

**Comment by lfelipe** [comment]
Yes, that should likely just go through the standard download website and we can from cockpit just mention whats the latest release available at some point.
