### ISSUE TITLE
Aero RTF v1.4 - Realsense camera not detected

### ISSUE THREAD

**Issue by lajoiepy** [intel-aero/meta-intel-aero#222]
Hi!
I recently flashed the new image (v1.4) on the Aero RTF of my lab and unfortunately, I am not able to start the Realsense R200 camera from the Docker container because the camera is not detected. I followed this [tutorial](https://github.com/intel-aero/meta-intel-aero/wiki/08-Aero-Network-and-System-Administration) and I chose the aero-ros image. Note : I am able to see the camera images with `gst-launch-1.0 v4l2src device=/dev/video13 ! xvimagesink`.
TL;DR
```
$ docker run -i -t my_folder/aero-ros /bin/bash
$ roslaunch realsense_camera get_debug_info.launch
...
----------CUT-PASTE-THIS----------
|Version | Your Configuration |
|:----------|:----------|
|Operating System | Ubuntu 16.04.2 LTS|
|Kernel | 4.4.67-yocto-standard|
|ROS | kinetic|
|ROS RealSense | 1.8.0|
|librealsense | 1.12.1|
|Camera Type-Firmware | No Cameras Detected |
----------CUT-PASTE-THIS----------
================================================================================REQUIRED process [data_collection-2] has died!
process has finished cleanly
log file: /root/.ros/log/bb751b3a-6cc4-11e7-ae27-0242ac110002/data_collection-2*.log
Initiating shutdown!
================================================================================
```

**Comment by lucasdemarchi** [comment]
You need to pass `--privileged` to access all devices from host.

**Comment by lajoiepy** [comment]
Thank you!
