### ISSUE TITLE
Change IP subnet for wifi

### ISSUE THREAD

**Issue by lucasdemarchi** [intel-aero/meta-intel-aero#23]
USB ethernet uses 192.168.7.x subnet which avoids conflicts with common used ranges. However the WiFi AP uses 192.168.1.x which makes it difficult to use when you have to wifi adapters on your computer and want to use one to keep connected to the internet.

**Comment by magicrub** [comment]
I'd like to suggest we use 192.168.2.x (or 192.168.6.x)

**Comment by vilvo** [comment]
Patches welcome :)

**Comment by lucasdemarchi** [comment]
I'm going with 192.168.8.x

**Comment by magicrub** [comment]
192.168.8.x works for me. Thank you! I had changed mine to 2.x because it was extremely annoying to work with my laptop while on a docking station /w Ethernet on my 1.x LAN.

**Comment by lucasdemarchi** [comment]
Fixed, it's now 192.168.8.x
