### ISSUE TITLE
aero-rtf.jam from July 26th has FPGA version 0X80

### ISSUE THREAD

**Issue by gjkunde** [intel-aero/meta-intel-aero#245]
The older version was 0xC0, did I get the right copy ? I downloaded from 
https://github.com/intel-aero/meta-intel-aero/tree/master/recipes-support/jam-stapl/jam-stapl

**Comment by anselmolsm** [comment]
@zehortigoza could you please check that?

**Comment by zehortigoza** [comment]
Check this: https://github.com/intel-aero/meta-intel-aero-base/commit/992d7a518436705f3510bcb91e4c536f100a15af

**Comment by gjkunde** [comment]
Thanx, indeed, that is working, would be good to suggest on the wiki to a download
of the recipes-support/scripts/files/aero-get-version.py when they
get the new firmware.

**Comment by zehortigoza** [comment]
The FPGA firmware and this script will be officially release in the next Intel Aero BSP release.
