### ISSUE TITLE
No GPS and no adc0 in FPGA firmware Version 0xC1 

### ISSUE THREAD

**Issue by gjkunde** [intel-aero/meta-intel-aero#247]
Dear All,

when I compared the nuttshell command 'ls /dev' 
for 0xC0 and 0xC1 I got identical list but for the 'adc0',
it is not present in 0xC1. Is that the battery adc on the
I2C bus ?

**Comment by gjkunde** [comment]
In addition to the missing adc0 there is no GPS information
visible in QGC, neither in the icon nor in the instrument panel.

Reverting back to 0xC0 restores both GPS and adc0.

**Comment by zehortigoza** [comment]
https://github.com/intel-aero/meta-intel-aero/issues/221#issuecomment-319520005

you need to update PX4 as well.

**Comment by gjkunde** [comment]
I did a GIT pull of the PX4 firmware and made aerofc and uploaded,
what else am I missing ?

**Comment by lucasdemarchi** [comment]
On nsh console type:
ver git

And report the version.

**Comment by zehortigoza** [comment]
> I did a GIT pull of the PX4 firmware and made aerofc and uploaded,
what else am I missing ?

Always run a 'make clean' after you fetch new commits this will guarantee that any changes in defconfig will be applied.

**Comment by gjkunde** [comment]
1.6.5 0 (17171712)

**Comment by gjkunde** [comment]
v1.6.5-350-ge7b7b27

**Comment by zehortigoza** [comment]
> FW git-hash: e7b7b27ef8b0dbf67b5ecda3b9d1c382a73193bc

The patches enabling it was merged after this patch.

**Comment by zehortigoza** [comment]
If you want to try the firmware that is going to be part of our release try with this one: https://github.com/intel-aero/meta-intel-aero/pull/249

**Comment by gjkunde** [comment]
Thank you, could you please add I2C to nuttx in your release ? I am going
to clone it and try.

**Comment by gjkunde** [comment]
OK, I cloned https://github.com/intel-aero/meta-intel-aero/pull/249
git describe
v1.3.0rc1-3922-ge7d801c
I uploaded it onto the RTF alas I cannot talk to it anymore,
neither via ground control nor with Tools/mavlink_shell.py 0.0.0.0:14550
Does your version have a different baud rate ?
