### ISSUE TITLE
GPS unit is turnable on mast (potentially causing issues for the flight controller)

### ISSUE THREAD

**Issue by LorenzMeier** [intel-aero/meta-intel-aero#250]
We've had a few units where the top GPS cover is loose. A direction change there is problematic with the in-built compass and could cause toilet-bowling or other symptoms of deteriorated flight performance.

**Comment by lucasdemarchi** [comment]
Yep. This is a known issue. We should add that to the new docs and suggest how to fix it. Thanks.

**Comment by suraj1988** [comment]
Hello. Im currently experiencing similar issues on my quad which i suspect may be due to this.  Any suggestions for working around this ?

**Comment by lucasdemarchi** [comment]
Make sure the screw is tight (note there's a small hex screw in the mast). Better yet put a little bit so it doesn't turn.

**Comment by lucasdemarchi** [comment]
Closing this as it is a hardware limitation that can't really be fixed, but should have be workarounded.
