### ISSUE TITLE
sd_bench missing in nuttx and other sd card problems

### ISSUE THREAD

**Issue by gjkunde** [intel-aero/meta-intel-aero#253]
Dear All,

we tried to use a SD card in the slot that is externally accessible,
both FAT formatted 8 and 64 GByte cards. Set QGC to logging
but there is nothing on the cards. I am not sure they are recognized.
In trying to debug from nsh it appears that sd_bench is missing ...
and I do not see the sd card under /dev ? What is the proper
format for the card ? How can I verify that it is mounted ? It
appears that there are no sd card specific settings in defconfig ?
Where do I set SYS_Logger to 1 and what role do the settings in
QGC play. When I say 'logger status' it tells me with w/o or with
card always 'mavlink logging' ... Thanks Gerd

**Comment by zehortigoza** [comment]
The SD card in Aero is connected to Intel Atom not to AeroFC, so you should try to mount the SD card from Linux.
The AeroFC logs is already streamed to Linux, just look at the log files in /var/lib/mavlink-router/
