### ISSUE TITLE
Can't connect to QGroundControl

### ISSUE THREAD

**Issue by Aurusd** [intel-aero/meta-intel-aero#261]
Update intel aero drone firmware to 1.4 version, like here https://github.com/intel-aero/meta-intel-aero/wiki/02-Initial-setup#flashing
But after this cant connect from qgroundcontrol to drone. Connect to drone AP wifi occurred   next problem
![clip2net_170811163956](https://user-images.githubusercontent.com/10154188/29216077-100ad4b6-7eb6-11e7-9c94-61c28d58545d.png)
I am not find how can to see current mavlink baud rate of qgroundcontrol  app. Try to change mavlink baud rate on drone (in this file /etc/mavlink-router/main.conf), but error still present. 
Also try to use usb cable (RNDIS ethernet gadget) qgroundcontrol  show nothing. Test on win 7

**Comment by zehortigoza** [comment]
I saw this issue that you opened in PX4 https://github.com/PX4/Firmware/issues/7765 maybe you loaded a PX4 firmware targeted to other board. If so please follow the recovery process: https://github.com/intel-aero/intel-aero-docs/pull/33 following method 2.
QGroundControl should connect to AeroFC without any changes on the mavlink-router configuration file.

If even after you load the PX4 firmware that comes with the image the communication with QGC did not work please run this and paste the output:
```
systemctl stop mavlink-router
mavlink-routerd -r
```

**Comment by Aurusd** [comment]
When i bought drone i have version lower than 1.2, i then i have flashed the last version 1.4 https://downloadcenter.intel.com/download/26932/Intel-Aero-Platform-for-UAVs-Installation-Files
After i cant connect via QGC. 
ifconfig 
![clip2net_170815071417](https://user-images.githubusercontent.com/10154188/29305656-84c4258e-81a2-11e7-9e16-d507ec8c6d6f.png)
systemctl stop mavlink-router
mavlink-routerd -r
[log_mavlink_routerd.txt](https://github.com/intel-aero/meta-intel-aero/files/1224408/log_mavlink_routerd.txt)

**Comment by zehortigoza** [comment]
By the logs there is some problem between Aerofc and mavlink-routerd. Did you changed the baudrate in the configuration file?
The latest version is 1.5.1v try update to that, including PX4, FPGA and BIOS of the same release.

**Comment by Aurusd** [comment]
yes, i have changed baud rate, by default in configuration file was 468000, i changed to 57600. Ok i will try

**Comment by Aurusd** [comment]
update for version 1.5.1. But even from phone app QGC cant connect, i saw drone icon on map, but on app have text - Waiting for Vehicle connection (connect to drone wifi AP, and put password 1234567890)

**Comment by Aurusd** [comment]
i have said not true, on phone its work! but on win10 no

**Comment by Aurusd** [comment]
for now it works!
