### ISSUE TITLE
Intel Aero switch from Mavlink 2.0 to 1.0

### ISSUE THREAD

**Issue by Aurusd** [intel-aero/meta-intel-aero#270]
Have intel Aero drone, and code for work with mavlink 1.0. AeroFC work on Mavlink 2.0, and i have changed my code, run and received right packets from FC. I dont know exactly what i do next, but then i reboot drone and run code again, i received packet in mavlink 1.0. AeroFC i dont know how switched to 2.0. 
Can somebody explain how to changes mavlink version protocol? 
OS version:1.5.1

**Comment by anselmolsm** [comment]
Not sure what you meant by "AeroFC i dont know how switched to 2.0".

Check if [this documentation](https://github.com/mavlink/mavlink/blob/master/doc/MAVLink2.md) helps you.
