### ISSUE TITLE
Flight Modes Description

### ISSUE THREAD

**Issue by Aurusd** [intel-aero/meta-intel-aero#274]
I cant find flight modes description. Use intel aero drone. In heartbeat message received
base_mode = 81;
custom_mode = 84148224;
Where i can find description of this options to determine flight mode?

**Comment by zehortigoza** [comment]
https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_messages.cpp#L118

**Comment by anselmolsm** [comment]
@zehortigoza isn't there any doc page to link with the description? So that link could be added to Aero's docs.

**Comment by zehortigoza** [comment]
It is specific to each autopilot, I did a quick search in the PX4 wiki and I didn't find any documentation with the id of the modes.
