### ISSUE TITLE
Intel aero // Mavros - Clock skew detected

### ISSUE THREAD

**Issue by ChriSil** [intel-aero/meta-intel-aero#275]
Hi all,

when establishing a mavros connection between my Laptop (Ubuntu 16.04 LTS , running ros), and the Intel Aero RTF via UDP

$ roslaunch mavros px4.launch fcu_url:="udp://0.0.0.0:14550@192.168.0.73:14556"          (IP of drone in local network)

the console yields the following

[ INFO] [1505308969.287351579]: MAVROS started. MY ID 1.240, TARGET ID 1.1
[ WARN] [1505308969.372640545]: TM: Clock skew detected (-1505308694.417684555 s). Hard syncing clocks.
[ INFO] [1505308969.393820707]: IMU: High resolution IMU detected!
[ INFO] [1505308969.393991552]: IMU: Attitude quaternion IMU detected!
[ INFO] [1505308969.727654561]: CON: Got HEARTBEAT, connected. FCU: PX4 Autopilot
[ INFO] [1505308970.051755980]: IMU: High resolution IMU detected!
[ INFO] [1505308970.052007967]: IMU: Attitude quaternion IMU detected!
[ INFO] [1505308970.740422861]: VER: 1.1: Capabilities         0x00000000000024ef
[ INFO] [1505308970.740548486]: VER: 1.1: Flight software:     01060500 (000000000181F900)
[ INFO] [1505308970.740654226]: VER: 1.1: Middleware software: 01060500 (000000000181F900)
[ INFO] [1505308970.740712155]: VER: 1.1: OS software:         000000c0 (0000000000000000)
[ INFO] [1505308970.740770259]: VER: 1.1: Board hardware:      0000a4a7
[ INFO] [1505308970.740831751]: VER: 1.1: VID/PID:             0525:a4a7
[ INFO] [1505308970.740884032]: VER: 1.1: UID:                 3335511839343335
[ WARN] [1505308970.740974275]: CMD: Unexpected command 520, result 0
[ WARN] [1505308979.375366479]: TM: Clock skew detected (7718063342.435769081 s). Hard syncing clocks.
[ INFO] [1505308979.728118434]: HP: requesting home position
[ INFO] [1505308984.735264665]: WP: mission received
[ WARN] [1505308989.471157623]: TM: Clock skew detected (-7718063342.437295914 s). Hard syncing clocks.
[ INFO] [1505308989.728430551]: HP: requesting home position
[ WARN] [1505308999.473095008]: TM: Clock skew detected (7718063342.437585831 s). Hard syncing clocks.
[ INFO] [1505308999.728594636]: HP: requesting home position

Executing the mavros topic "time_reference"

$ rostopic echo /mavros/time_reference

yields the following:

header: 
  seq: 201
  stamp: 
    secs: 1505309160
    nsecs: 267349839
  frame_id: ''
time_ref: 
  secs: 1505309160
  nsecs: 265019000
source: fcu
---
header: 
  seq: 202
  stamp: 
    secs: 1505309161
    nsecs: 304928103
  frame_id: ''
time_ref: 
  secs: 1505309161
  nsecs: 265189000
source: fcu
---

now, my question: what is the reason for the Clock skew, and how can I fix it, as I believe it prevents my /mavros/mocap/pose data to be transfered to the drone, and thus, to appear in the RTFs logfiles.

regards,
Christopher

Issue has also been posted on the "Intel® Aero Platform for UAVs", 
https://communities.intel.com/thread/117934

**Comment by shakthi-prashanth-m** [comment]
Hi Christopher, could you set `conn/timesync_rate` to 0  in `px4_config.yaml` ?
Its path should be `mavros/launch/px4_config.yaml`.
