### ISSUE TITLE
Connect 4g modem telit ln930

### ISSUE THREAD

**Issue by Aurusd** [intel-aero/meta-intel-aero#276]
Have any body some experience or tutorial how to configure and use telit ln930 or same m2 modem with intel aero drone?

**Comment by guermonprez** [comment]
should be online today or monday, thanks

**Comment by Aurusd** [comment]
On my computer board version i have plug modem without problem. But on yocto linux 1.5.1 i haven't seen any telit device (no lsusb, no lspci). What i have missed? maybe i need to build my own yocto image with ither drivers. Have anybody advices? maybe there isn't some drivers, cause this modem not also not detected

**Comment by Aurusd** [comment]
on this guide https://www.intel.com/content/dam/support/us/en/documents/boardsandkits/aero/aero-platform-uavs-mechanical-assembly-guid…  i have connect telit modem to R RESERVED for future use maybe itsn't m.2, cause on 13 M.2 Interface for PCIe SSD there is pins mismatch beetwen telit modem and computer board

**Comment by Aurusd** [comment]
maybe i need to activate R RESERVED or its not work actually?
![clip2net_170924172927](https://user-images.githubusercontent.com/10154188/30783583-f85de8f2-a14d-11e7-9fd6-b51b36db8e6b.png)

**Comment by Aurusd** [comment]
And there is a big question second m2 socket type B marked on https://www.intel.com/content/dam/support/us/en/documents/boardsandkits/aero/aero-platform-uavs-mechanical-assembly-guide.pdf​
like R Reserved and socket for sim card actually is active or empty?

**Comment by broody** [comment]
Hi Ausurd, have you updated BIOS as well? v01.00.13 is needed.

**Comment by avinash-palleti** [comment]
@Aurusd As @broody mentioned v01.00.13 bios is required to get Modem working. Below are the slots for both modem and SIM card,

![modem](https://user-images.githubusercontent.com/362099/30791067-b1633b16-a1cd-11e7-9c36-9b4d8e5d216e.png)
You actually need a SIM card holder one like below to insert into respective slot,
![sim_holder](https://user-images.githubusercontent.com/362099/30791078-c7a90aa4-a1cd-11e7-93fd-aef62764e628.jpg)

Further if you face any issues in connecting to live network, you might need to update APN as per your operator. Please find the steps to update APN at https://github.com/intel-aero/meta-intel-aero/wiki/08-Aero-Network-and-System-Administration#networking-lte

**Comment by Aurusd** [comment]
Ok.. thanks for advise i will try.

**Comment by Aurusd** [comment]
Modem now detect correctly!!)) There is somethere document which describe bios version firmware (what support and what no) or i can only solve my problem by publish issue on github?

**Comment by lucasdemarchi** [comment]
Only the latest bios (1.00.13) with latest bsp (1.5.1). FC firmware can be any one
