### ISSUE TITLE
which aerofc is more up-to-date

### ISSUE THREAD

**Issue by gzhang8** [intel-aero/meta-intel-aero#280]
There are one in /etc/px4-fw/ and one in /etc/aerofc/ . Why there are two?
Also I see aerofc-update and aerofc_update

**Comment by lucasdemarchi** [comment]
they should be symlinks to each other to preserve old names. In the beginning we only supported PX4. Now we support PX4 and ArduPilot,  so we moved things to /etc/aerofc, but added symlinks in /etc/px4-fw to avoid breaking other tools

**Comment by anselmolsm** [comment]
In other words, /etc/px4-fw and /etc/aerofc content is the same.
aerofc-update and aerofc_update are two names for the same script.
Thanks.

**Comment by gzhang8** [comment]
I see, thanks for your clarification  @lucasdemarchi  @anselmolsm
