### ISSUE TITLE
Problem building the image with Yocto Krogoth

### ISSUE THREAD

**Issue by PabloMIntel** [intel-aero/meta-intel-aero#3]
The git clone command for getting the meta-intel layer was missing the -b krogoth flag. It would be a good idea to add that to the instruction to avoid getting the master branch of the layer instead of the Krogoth

**Comment by intel-aero** [comment]
Currently, we are using master branch on meta-intel due to a dependency. Please use below commands to clone meta-intel:

git clone git://git.yoctoproject.org/meta-intel
cd meta-intel; git checkout 5326759e90180523da3617becfab4a7e21d7ebde; cd $POKYSRC
