### ISSUE TITLE
Not able to connect with QGroundControl 

### ISSUE THREAD

**Issue by mandelyoni** [intel-aero/meta-intel-aero#309]
Hi, 

I'm not able to connect with QGroundControl, after installing Ubuntu,  according to  90 (References) OS user Installation · intel-aero/meta-intel-aero Wiki · GitHub 
I receive the attached response:
"vehicle did not respond to request for parameters. This will cause qgroundcontrol to be unable to display its full interface"
![vehicle1](https://user-images.githubusercontent.com/4273822/36374215-3d2c78ba-1573-11e8-9e58-2f64518b2417.jpg)

**Comment by lmicko** [comment]
Hi, I've faced the same issue. Didn't have much time to figure out what's wrong, but using previous version of QGC worked well.

**Comment by mandelyoni** [comment]
it worked
version 3.2.7 of QGC is good

thank you

**Comment by anitha-suresh** [comment]
Closing this issue, as I see it works for Yoni now.
