### ISSUE TITLE
Pixhawk2

### ISSUE THREAD

**Issue by Thanos254** [intel-aero/meta-intel-aero#311]
Can I connect PIxhawk2 FC with the Intel Aero?

**Comment by anitha-suresh** [comment]
@Thanos254, yes!

@sugnanprabhu , can you please provide your inputs

**Comment by sugnanprabhu** [comment]
Please check the following documentation which is for pixhawk which is applicable for pixhawk2 as well.
https://github.com/intel-aero/meta-intel-aero/wiki/93-(References)-Pixhawk-FC

**Comment by JustFineD** [comment]
Hi, I was able to connect pixhawk1 to the aero using UART. 
Unfortunately when I tried to connect pixhawk2 (cube) - I wasn't able to make a connection to the aero

**Comment by sugnanprabhu** [comment]
@JustFineD what pins are you connecting from pixhawk2 to compute board?
You can try connecting the TELEM pin, make sure to use the correct baud rate and telmetry pin is configured to get the mavlink messages.
