### ISSUE TITLE
ROS installation problem

### ISSUE THREAD

**Issue by mandelyoni** [intel-aero/meta-intel-aero#316]
Hi,

while installing ROS according to https://github.com/intel-aero/meta-intel-aero/wiki/05-Autonomous-drone-programming-with-ROS,    we receive the error in the pic attached.

Any idea what to do?

Thank you

![ros_prob](https://user-images.githubusercontent.com/4273822/36478537-cc7b3c04-170d-11e8-8d7b-3fca718b9cf6.jpg)
?

Thank you,  Yoni.

**Comment by shakthi-prashanth-m** [comment]
Hi Yoni,
If you experience issues connecting to the keyserver, you can try substituting hkp://pgp.mit.edu:80 or hkp://keyserver.ubuntu.com:80 in the previous command.

as suggested in ROS-Kinetic Ubuntu installation guide: http://wiki.ros.org/kinetic/Installation/Ubuntu

**Comment by mandelyoni** [comment]
Thanks, I wrote this:

sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116

**Comment by shakthi-prashanth-m** [comment]
OK! @mandelyoni were you able to install successfully ?

**Comment by mandelyoni** [comment]
Yes, thank you

**Comment by shakthi-prashanth-m** [comment]
Closing as issue resolved.

**Comment by mymultiverse** [comment]
I am getting following message.

```
gpg: requesting key B01FA116 from hkp server pgp.mit.edu
gpg: key B01FA116: "ROS Builder <rosbuild@ros.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1

```

```
gpg: requesting key B01FA116 from hkp server keyserver.ubuntu.com
gpg: key B01FA116: "ROS Builder <rosbuild@ros.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```
