### ISSUE TITLE
memory leak in the Intel Aero

### ISSUE THREAD

**Issue by shai91521** [intel-aero/meta-intel-aero#317]
Hi, 

**I followed your instructions on** 
https://github.com/intel-aero/meta-intel-aero/wiki/90-(References)-OS-user-Installation#choice-of-oses
**up to (and including)** 
https://github.com/intel-aero/meta-intel-aero/wiki/90-(References)-OS-user-Installation#intel-realsense-sdk 

and then I noticed there is a memory leakage - please see attached pictures at consecutive times (look at the watch) :

![mem leak 1](https://user-images.githubusercontent.com/36698447/36479557-cf2cfe2a-1711-11e8-8246-0d43aa2abfe2.jpg)
![mem leak 2](https://user-images.githubusercontent.com/36698447/36479581-df5a43b6-1711-11e8-9118-cc5ea7c1d94a.jpg)

What do you think?

Thank you

**Comment by lucasdemarchi** [comment]
This is a picture showing the storage used, not ram.

**Comment by mandelyoni** [comment]
I know
It still doesn't solve the problem  :)

**Comment by anselmolsm** [comment]
There is a problem in the problem statement.
Memory leak is related to RAM, not storage.
The only conclusion from the pictures is that the system is using +100MB of **storage** after 57 minutes.
