### ISSUE TITLE
Micro Servo + Intel Aero

### ISSUE THREAD

**Issue by troylumpkin** [intel-aero/meta-intel-aero#322]
I'm hoping to connect a Micro Servo to my Intel Aero RTF.  Does anyone know how one might do that?

**Comment by zehortigoza** [comment]
There is no general purpose pins exported in Aero RTF, so I would say to you use the telemetry connector for that, you will have to edit the PX4 firmware, remove the mavlink from that port, remove the UART function from that port, configure the pin as PWM then you can use mavlink message to control the servo from QGC or any application. There is nothing ready and I can tell you that will not be easy, good luck.
