### ISSUE TITLE
SYS_HITL mode jMavSim - WARN  [commander] rejecting takeoff, no position lock yet. Please retry.

### ISSUE THREAD

**Issue by trgiman** [intel-aero/meta-intel-aero#324]
Hello. I am about to run HITL (Hardware In The Loop simulation).  I am about to use jMavSim. But it seems, that QGround Control and jMavsim are not talking to each other. Below are the steps I have done recently

1. Trough Nuttx Shell I set param set SYS_HITL 1

2.But in QGround Controll I am not able to change to HIL Quadcopter X (i think this is the issues?)..Than I switch off QGC

1. Running ./jmavsim_run.sh -i 192.168.8.1 -r 250 on Ubuntu - Simulator starts and it seems it is connected trough UDP (according the sh script code) to the Intel Aero FC specifically using port 14560 for simulation (is there some parameter to see, that mavlink messages are really send?)

2. Than I run QGround connected trough UDP - default configuration

a) I can not take-off with QGround Controll. When RC connected I can only Arm and Disarm. When I try to run command commander takeoff from Nuttx shell...message is

**WARN  [commander] rejecting takeoff, no position lock yet. Please retry..**

Any suggestions please?

**Comment by zehortigoza** [comment]
This is not related to Aero, please open a issue in PX4.
