### ISSUE TITLE
pxflow not working

### ISSUE THREAD

**Issue by mandelyoni** [intel-aero/meta-intel-aero#325]
Hi,

I'm working according  to :

Intel Aero Drone - Altitude and Position Hold Using PX4Flow: 11 Steps (with Pictures) 

but I have no connection with the QGC after all the installations.

Any idea?

Thanks,  Yoni.

**Comment by trgiman** [comment]
hi @mandelyoni all solutions you need to solve it are here https://github.com/intel-aero/meta-intel-aero/issues/320

**Comment by mandelyoni** [comment]
Is it working on your drone?
It looks like the problem isn't solved

**Comment by mandelyoni** [comment]
Hi, can someone please assist?

**Comment by mandelyoni** [comment]
Hi,
Was someone able to operate the px4flow according to
http://www.instructables.com/id/Intel-Aero-Drone-Altitude-and-Position-Hold-Using-/ ?

What firmare did you use on the PX4 and the FPGA?
What QGC version?
any other modifications?

Thank you

**Comment by trgiman** [comment]
Hi @mandelyoni  yes it works. Tutorial you mentioned is old in regards of software setup. Follow https://github.com/intel-aero/meta-intel-aero/issues/320

**Comment by mandelyoni** [comment]
Great, thank you

**Comment by mandelyoni** [comment]
Hi Trgiman,

The instructions at #320  are not so clear to us.
Can you please summarize your solution?

Thank you very much,  Yoni,

**Comment by sluthra1** [comment]
Hello, I am a little confused on what was done in #320, can someone clarify the steps they took to get px4flow working?
