### ISSUE TITLE
PX4Flow not working

### ISSUE THREAD

**Issue by mandelyoni** [intel-aero/meta-intel-aero#327]
Hi,

Was someone able to operate the px4flow according to
http://www.instructables.com/id/Intel-Aero-Drone-Altitude-and-Position-Hold-Using-/    ?

What firmare did you use on the PX4 and the FPGA?
What QGC version?
any other modifications?

Thank you

**Comment by zehortigoza** [comment]
dublicated https://github.com/intel-aero/meta-intel-aero/issues/325
