### ISSUE TITLE
Mavlink-router port 14560 to use HITL mode of PX4 is not working

### ISSUE THREAD

**Issue by trgiman** [intel-aero/meta-intel-aero#329]
Hi. I am trying to connect to port 14560 to /dev/ttyS1 of Yocto from my development workstation(Ubuntu) in order to be able to use HITL simulation (SYS_HITL in PX4 enabled). But am not getting any MavLink responses.

Any suggestions how to change /etc/mavlink-router/main.conf? I tried to add PORT = 14560,where appropriate according help. But it seems, there is no change.

**Comment by lucasdemarchi** [comment]
Please open an issue in mavlink-router

**Comment by trgiman** [comment]
Ok. Moved
