### ISSUE TITLE
Request for USB3 OTG Cable

### ISSUE THREAD

**Issue by mgildner** [intel-aero/meta-intel-aero#330]
Hi,

Is there anyway I can purchase several USB3 compatible OTG cables so that I may connect USB3 sensors to the compute board OTG port?  Such cables are mentioned on the wiki several times, but it is not clear where they can be purchased.  Without them I am unable to connect USB3 sensors successfully to the compute board.

**Comment by zehortigoza** [comment]
@ktadros ?

**Comment by zehortigoza** [comment]
https://click.intel.com/usb-3-0-otg-cable-for-the-intel-aero-platform.html
