### ISSUE TITLE
Garmin Lidar Lite for optic flow does not run and exits with error code 'exit-code'

### ISSUE THREAD

**Issue by ashirsat** [intel-aero/meta-intel-aero#335]
Hi,

I am trying to connect the Garmin Lidar Lite on the intel aero for getting optical flow data using this guide as suggested in the following [link](https://communities.intel.com/thread/122713).
When I do start the service using 
`systemctl start aero-optical-flow` 
I get the following error message.

`● aero-optical-flow.service - Aero optical flow
   Loaded: loaded (/lib/systemd/system/aero-optical-flow.service; disabled; vendor preset: enabled)
   Active: inactive (dead)

Apr 05 11:00:38 intelaero aero-optical-flow[2483]:         focal_length_y=216.245697
Apr 05 11:00:38 intelaero aero-optical-flow[2483]: [Error] Getting exposure: Invalid argument
Apr 05 11:00:38 intelaero aero-optical-flow[2483]: [Error] Unable to initialize camera
Apr 05 11:00:38 intelaero systemd[1]: aero-optical-flow.service: Main process exited, code=exited, status=255/n/a
Apr 05 11:00:38 intelaero systemd[1]: aero-optical-flow.service: Unit entered failed state.
Apr 05 11:00:38 intelaero systemd[1]: aero-optical-flow.service: Failed with result 'exit-code'.
Apr 05 11:00:38 intelaero systemd[1]: aero-optical-flow.service: Service hold-off time over, scheduling restart.
Apr 05 11:00:38 intelaero systemd[1]: Stopped Aero optical flow.
Apr 05 11:00:38 intelaero systemd[1]: aero-optical-flow.service: Start request repeated too quickly.
Apr 05 11:00:38 intelaero systemd[1]: Failed to start Aero optical flow.
`

I tried to see if there was a hardware issue. So I replaced the lidar with a new one. 
But this also does not help.

The firmware on the intel -aero is as follows
`BIOS_VERSION = Aero-01.00.13
OS_VERSION = Ubuntu 16.04.4 LTS"
AIRMAP_VERSION = unknown
FPGA_VERSION = 0xc2
AeroFC firmware version = 1.6.5
'
Please let me know how could i resolve this issue.

Thanks,

Aniket

 @zehortigoza 
 @lucasdemarchi

**Comment by zehortigoza** [comment]
aero-optical-flow has nothing to do with lidar, lidar is connected directly to FC you need to check in PX4 is being able to readings from lidar.

About this error, looks like aero-optical-flow is not being able to find and initialize the camera. Please check the connection of both cameras(if the HD is disconnected the down-faced camera will have a different ID causing this problem), also check if there is something using the cameras? Like streaming any of the cameras to QGC? Only one application can have access to both cameras.
