### ISSUE TITLE
Librealsense cpp examples don't run

### ISSUE THREAD

**Issue by ivanalexo** [intel-aero/meta-intel-aero#338]
When I installed the SDK for Intel RealSense, I used the next commands:
sudo apt-get -y install git libusb-1.0-0-dev pkg-config libgtk-3-dev libglfw3-dev cmake
git clone -b legacy --single-branch https://github.com/IntelRealSense/librealsense.git
cd librealsense
mkdir build && cd build
cmake ../ -DBUILD_EXAMPLES=true -DBUILD_GRAPHICAL_EXAMPLES=true
make
sudo make install
As it mentions on the wiki... after that I wanted to test the examples but doesn't execute 
First I wanted to test "cpp-enumerate-devices" 
Second with "cpp-capture" but showed me error.

**Comment by zehortigoza** [comment]
Please give more information like the error messages.
