### ISSUE TITLE
NOT WORKING: Take a photo with the black and white camera

### ISSUE THREAD

**Issue by MathiasDePaepe** [intel-aero/meta-intel-aero#340]
When I run the following commands

git clone https://github.com/intel-aero/sample-apps.git
cd sample-apps/capturev4l2/
make
C=10 INPUT=1 MODE=PREVIEW ./capture_v4l2 --userp -d /dev/video2
ffmpeg -f rawvideo -s 640x480 -pix_fmt yuv420p -i Image-video<*> test.jpg

There is no problem until the last command to make from a yuv file a jpg file. I got the error -bash: *: ambiguous redirect

How to solve this problem?

**Comment by lbegani** [comment]
Replace `Image-video<*>`  in the below command with real file name
`ffmpeg -f rawvideo -s 640x480 -pix_fmt yuv420p -i Image-video<*> test.jpg`

**Comment by MathiasDePaepe** [comment]
Thanks a lot, it works!
