### ISSUE TITLE
Hotspot Wifi Aero lost

### ISSUE THREAD

**Issue by MathiasDePaepe** [intel-aero/meta-intel-aero#342]
By default there is an access point with SSID Aero-. When i connected to my home wifi like discribed in the tutorial, i lost my hotspot and the original acces point has disapeared. 
When exectuting `nmcli c up hotspot` i got the error `Connection 'hotspot' does not exist.`

As solution i would reinstall the

> intel-aero-image-intel-aero-1.6.1.iso

, but is there an other solution?

Thanks on advance!

**Comment by zehortigoza** [comment]
https://github.com/intel-aero/meta-intel-aero/wiki/08-Aero-Network-and-System-Administration#wifi-factory-reset

**Comment by MathiasDePaepe** [comment]
When executing ```
rm /etc/sysconfig/networkmanager
reboot
```

I got the message:
`rm: cannot remove 'etc/sysconfig/networkmanager': no such file or directory`

I reinstalled intel aero and ubuntu but that didn't solved the problem

**Comment by MathiasDePaepe** [comment]
When reexamining the install procedure of intel and ubuntu like described in the tutorial, the hotspot returned.
