### ISSUE TITLE
Intel Aero with UWB positioning moving can't hover in position control mode

### ISSUE THREAD

**Issue by valtsblukis** [intel-aero/meta-intel-aero#343]
We've been trying to use the Intel Aero drone with Pozyx positioning indoors. We are using the local position estimation (LPE) mode on the PX4 stack and have made sure that we get a reliable, stable estimate at about +/-10cm that smooths out most of the noise. However, when we try to fly the drone in position control mode, it moves around wildly within +-1.5 meters from the position setpoint. Given that the position estimate is fairly stable, it seems like the issue might be with controller tuning. I wonder if anyone has successfully been able to achieve stable hovering indoors with UWB (Pozyx or otherwise).

Thanks!

**Comment by lucasdemarchi** [comment]
The correct place to file this issue is in the PX4 project, where you will have more feedback.
