### ISSUE TITLE
Add version to FPGA firmware

### ISSUE THREAD

**Issue by lucasdemarchi** [intel-aero/meta-intel-aero#35]

**Comment by lucasdemarchi** [comment]
@zehortigoza there's a version already on the compute-board-only fpga. Could you copy the version handling to the RTF version? You will also need to copy the spi slave implementation.

What's the version they are using there? Maybe we should have a "WHOAMI" register and a 16 bit version register.

**Comment by zehortigoza** [comment]
So the actual script send the WHOAMI register(0x00) then reads only 1 byte.
aero_sample is using 0xA1 as registor version so here https://github.com/intel-aero/intel-aero-fpga/pull/1
it is using 0xC1

**Comment by lucasdemarchi** [comment]
Yep, looks good for now.

**Comment by lucasdemarchi** [comment]
Please send  the update recipe.
