### ISSUE TITLE
dev/spidev* not found

### ISSUE THREAD

**Issue by abhi11796acharya** [intel-aero/meta-intel-aero#356]
Hello,

I installed latest version of yocto and everything was working fine. I was able to access all I2C and SPI buses. But after installing ubuntu, I am not able to access SPI buses. Whenever I try to the below mentioned command on shell, it throws an error saying "dev/spidev3.0 not found".

spi_xfer -b 3 -c 0 -d 0x80 -w 2

I followed the wiki page procedure to install ubuntu.
Kindly help me!!

Thank you!!

**Comment by abhi11796acharya** [comment]
how can I check this ..?

**Comment by Rjasuja** [comment]
Run `dpkg -s <package_name>` command

**Comment by abhi11796acharya** [comment]
yes it is installed. system is throwing following error:

ERROR: failed to open /dev/spidev3.0

When I searched for spidev3.0 in /dev directory, I didnt find it.

**Comment by abhi11796acharya** [comment]
I installed everything again and now spidev1.1 and spidev3.0 is present in the dev directory but I am still getting the same error when trying spi_xfer command on shell.

"ERROR: failed to open /dev/spidev3.0"

**Comment by abhi11796acharya** [comment]
I used sudo and now it is working.  :)

Thank you!!
