### ISSUE TITLE
Mavlink version

### ISSUE THREAD

**Issue by Huginn87** [intel-aero/meta-intel-aero#380]
Good morning,
I wanted to ask which version of mavlink uses the drone intel aero. If I updated yocto to version 1.6.2, would I update the mavlink version too?

**Comment by zehortigoza** [comment]
It support MAVLink 1 and MAVLink 2, the newest PX4 releases have the newest MAVLink 2 messages but there is no actual minor version in MAVLink to check. So just updating Yocto will not change anything, updating the flight stack firmware will.

**Comment by Huginn87** [comment]
Thank you very much for helping
