### ISSUE TITLE
Can the flying range of the Intel Aero be increased ?

### ISSUE THREAD

**Issue by RohanKurane** [intel-aero/meta-intel-aero#384]
Hello,

The current (default) range of the Intel Aero drone is 300 cubic meter. Is there anyway (programatically or hardware) to increase the flying range of it ? 

@lucasdemarchi 
@zehortigoza

**Comment by zehortigoza** [comment]
You mean the remote control range? You can replace the RC receiver and controller to one with a bigger range

**Comment by RohanKurane** [comment]
Yes, I meant remote control range. 

Do you have any suggestions on which remote control would be the best to use for the Intel Aero UAV ?

**Comment by lucasdemarchi** [comment]
Any RC that use the DSM protocol should work. For sbus you will need to put an inverter or change the fpga firmware.
