### ISSUE TITLE
where is the flight-log file?

### ISSUE THREAD

**Issue by Tenacity-soar** [intel-aero/meta-intel-aero#389]
i use the ardupilot firmware.  but i can not find the flight-log files by the QGroundControl
![image](https://user-images.githubusercontent.com/28495909/46927296-38ec0180-d067-11e8-9684-b4a969e34af6.png)
So where is the flight-log files?

**Comment by lucasdemarchi** [comment]
Probably a question for your flight stack or gcs. Please submit to the correct repo (px4, ardupilot or QGC.
