### ISSUE TITLE
Wiki: Application example in "Develop on Intel Aero" section should be updated to use devtool

### ISSUE THREAD

**Issue by whbruce** [intel-aero/meta-intel-aero#4]
**Issue Type:** Documentation feature request

**Summary:** Wiki: Application example in "Develop on Intel Aero" section should be updated to use devtool

**Description:** devtool is a Yocto tool that simplifies application development by generating recipes from source code, deploying resulting package and even allows building of image with that package included. See https://wiki.yoctoproject.org/wiki/Application_Development_with_Extensible_SDK#Creating_a_recipe_from_existing_source as an example. I can make changes if given access to wiki.

**Component affected:** Documentation

**Git tag tested**: N/A

**BIOS Version:** N/A

**Comment by intel-aero** [comment]
Thank you for bringing this to our attention. Updated documentation to reflect devtool info.
