### ISSUE TITLE
Add ArduPilot firmware besides PX4

### ISSUE THREAD

**Issue by lucasdemarchi** [intel-aero/meta-intel-aero#40]
PX4 is the flight stack coming on the FC. Adding both PX4 and ArduPilot binaries on the BSP allows to switch back and forth between them.

**Comment by avinash-palleti** [comment]
@anselmolsm @lucasdemarchi Adding v4 binary from below link will be fine i guess right ?

http://firmware.ap.ardupilot.org/Copter/2017-06/2017-06-01-04:06/PX4/

**Comment by lucasdemarchi** [comment]
No. It's aerofc. But I still need to submit a couple of changes there.

**Comment by zehortigoza** [comment]
https://github.com/intel-aero/meta-intel-aero/pull/170
