### ISSUE TITLE
Enable seemless flight stack logging

### ISSUE THREAD

**Issue by lucasdemarchi** [intel-aero/meta-intel-aero#41]
Mavlink Router already has capability to save the flight stack log (for PX4 is done, for ArduPilot is wip). Enable it by default on BSP.

**Comment by lucasdemarchi** [comment]
Done on mavlink-router. Just needs updated recipe.

**Comment by lucasdemarchi** [comment]
ok, #38 can be used for tracking the update.

**Comment by mindThomas** [comment]
But there is no seamless logging. There is a lot of dropouts if you start digging into the Ulog files or look at the terminal output from the logger.

**Comment by lucasdemarchi** [comment]
Dropouts are not related to who is saving the logs, but rather px4 not having enough bandwidth for what it's trying to save.

**Comment by mindThomas** [comment]
Alright. So your definition of 'seemless' does not include dropouts?

**Comment by lucasdemarchi** [comment]
You are commenting on an old issue/task that was related to adding the support for saving logs on the Linux side integrating the implementation done on mavlink-router.

There are issues with it that are not related with how we are saving the logs and there's an open issue about HSUART1 already.

**Comment by lucasdemarchi** [comment]
"Seamless" there was in the sense of how it's integrated... Maybe another word would have been better.
