### ISSUE TITLE
Stuck on black screen when installing ubuntu 16.04

### ISSUE THREAD

**Issue by yhdurkaya** [intel-aero/meta-intel-aero#419]
I am trying to install Ubuntu 16.04 following the guide. I use usb as the boot option. Everything is ok at this point but when I choose "Install ubuntu" or "Try ubuntu without installing"
 a black empty screen emerges and nothing happens. Has anyone encountered this problem before?

![123](https://user-images.githubusercontent.com/47098320/155164031-6759cd78-e70f-4b91-8782-1b9db8521cd2.jpg)

**Comment by afarrukh-emhr23** [comment]
Can you provide more details e.g what version of ubuntu are you using? What
error text you see on the black screen? Also provide a link to the online
documentation you were following.

**Comment by yhdurkaya** [comment]
I follow this documentation which I believe is the official one.
https://github.com/intel-aero/meta-intel-aero/wiki/90-%28References%29-OS-user-Installation

I am trying to install Ubuntu 16.04.

There is no error message. It just gets stuck on a black screen with nothing on it when I chooce "Install Ubuntu".

**Comment by afarrukh-emhr23** [comment]
Make sure you have the latest BIOS version by first installing the official
Yocto release:
https://www.intel.com/content/www/us/en/download/18793/26389/intel-aero-platform-for-uavs-installation-files.html?v=t

Also make sure that the Ubuntu 16.04 is the exact version as stated in the
wiki link you followed. i.e. 16.04.3.

**Comment by yhdurkaya** [comment]
The problem is that Ubuntu version that I used was 16.04.07. With Ubuntu 16.04.03, the problem didn't occur. 

Thanks @afarrukh-emhr23.
