### ISSUE TITLE
Cleanup layers

### ISSUE THREAD

**Issue by lucasdemarchi** [intel-aero/meta-intel-aero#43]
meta-intel-aero-* can be removed and the respective layers from yocto could be forked directly. Or depending on the package we could just have some .bbappend files. This way it's easier to see what's different from baseline and intel-aero

**Comment by lucasdemarchi** [comment]
First step is to move recipes from meta-intel-aero-connectivity to meta-intel-aero. @avinash-palleti can you take a look on this?

**Comment by avinash-palleti** [comment]
@lucasdemarchi, i will look into it

**Comment by avinash-palleti** [comment]
@lucasdemarchi, Can you check above patch. If it is Ok, i will send pull request.

I have kept recipes and bbappend files as it is into intel-aero. If required we can merge bbappend into original recipe files as well. for eg. images.bbappend from connectivity can be merged in images.bb of intel-aero.

**Comment by lucasdemarchi** [comment]
images.bbappend can probably be removed and merged into images.bb.

I didn't do the diff, but if you copied the files from their current location to meta-intel-aero, it's probably correct.

What still need to be done:

1. remove meta-intel-aero-connectivity from the manifest
1. add a commit to meta-intel-aero-connectivity doing the following:
    * remove everything
    * add a README.md saying content has been moved to meta-intel-aero

**Comment by whbruce** [comment]
Ideally hardware specific (i.e. BSP) recipes should be moved to a separate layer.

**Comment by lucasdemarchi** [comment]
on master-next
