### ISSUE TITLE
Add collision avoidance library

### ISSUE THREAD

**Issue by lucasdemarchi** [intel-aero/meta-intel-aero#45]
https://github.com/01org/collision-avoidance-library

**Comment by mbelluzzo** [comment]
- [ ] Move 'meta-coav' from coav's repo (we need a public repo for that)
- [ ] Add 'meta-coav' on meta-intel-aero (I have a scratch of this already)

**Comment by lucasdemarchi** [comment]
No more meta-*. Add it to meta-intel-aero

**Comment by mbelluzzo** [comment]
No way, coav needs its meta layer for its own reason. Also, coav isn't a product of intel aero, it makes no sense to maintain recipes to it there. We may have a custom recipe on meta-intel-aero that makes usage of meta-coav.

**Comment by lucasdemarchi** [comment]
If you are going to maintain a meta-coav, fine. I think it would be better if you go through the yocto's  standard layers than to keep your own layer for a single package. This would avoid problems like the one that happened for meta-librealsense vs meta-ros.

**Comment by lfelipe** [comment]
Something like meta-drones which includes mavlink-router, coav, camera streaming and possibly others would make sense. Then it would be easy for others to integrate this as a set (and it would serve as a location to integrate newer components as well).

**Comment by avinash-palleti** [comment]
@lucasdemarchi Shall i take up this? Is there any plan in place for this?

**Comment by anselmolsm** [comment]
@avinash-palleti PR #162
