### ISSUE TITLE
Enable support for package-based updates

### ISSUE THREAD

**Issue by lucasdemarchi** [intel-aero/meta-intel-aero#46]
rpm with dnf would be preferable.

**Comment by whbruce** [comment]
Recommended rpm package manger for krogoth is [smart](https://labix.org/smart). dnf is not available until Yocto 2.3.

**Comment by lucasdemarchi** [comment]
We may want to wait until 2.3 then. Or investigate other possibilities.

- swupd
- mender

I'd hate to go with smart now just to switch to dnf or something else in the other release.

**Comment by lucasdemarchi** [comment]
Assigning M1, but probably a future milestone

**Comment by lucasdemarchi** [comment]
Experimental support in v1.4 via dnf.
