### ISSUE TITLE
Add airspace managment data integration

### ISSUE THREAD

**Issue by airmapinc** [intel-aero/meta-intel-aero#5]
Issue Type: Feature/Enhancement

Summary: Add Airspace Data Access

Description: The AirMap airspace management system facilitates regulation conformity and notification compliance based on current location. Additionally, AirMap provides weather data, flight telemetry endpoint, and live alerts based on updated drone location.

Component: Airspace Management

BIOS version: 01.00.05

**Comment by intel-aero** [comment]
Integrated in release v01.00.02

**Comment by bansalma** [comment]
AirMAP 1.8 integrated in v01.00.04
