### ISSUE TITLE
Tools that should not be provided by busybox

### ISSUE THREAD

**Issue by lucasdemarchi** [intel-aero/meta-intel-aero#50]
This is a collection of tools that we keep adding here that should be provided by the original tools, not the cap'ed ones from busybox.
- ps
- tar

Just because it's horrible to use them and this should be developer-friendly.

**Comment by avinash-palleti** [comment]
[packages.xlsx](https://github.com/intel-aero/meta-intel-aero/files/893320/packages.xlsx)

Lucas,
Please find the data on packages which are from busybox.

**Comment by avinash-palleti** [comment]
@whbruce 
One query, as per below link the one with highest priority will go 
into final image.
 http://stackoverflow.com/questions/34609716/yocto-busybox-overriding-coreutils
But in case of tar & ps, i see their priority in meta/recipes-extended/tar and meta/recipes-extended/procps as 100 and 200 respectively, where as meta/recipes-core/busybox priority is 50 then why in final image these utilities came from busybox though its priority is less.

PS: meta layer is included in BBLAYERS.

**Comment by whbruce** [comment]
Your approach is not working as `tar` and `ps` are not provided by `coreutils` but their own recipes. You can determine this by looking at the content of `ALTERNATIVES` variable in the `coreutils` recipe and seeing they are not present.

Instead simply add the packages to the [core-tools packagegroup](../recipes-core/packagegroups/packagegroup-core-tools.bb). This works as both the `tar` and `procps` recipes set `ALTERNATIVE_PRIORITY` higher than busbox.

```
RDEPENDS_${PN} = "\
		..
		tar \
		procps \
		"
```

**Comment by avinash-palleti** [comment]
Thanks @whbruce for response. first approach will not work as these utilities are not provided by coreutils.
http://www.catonmat.net/download/gnu-coreutils-cheat-sheet.pdf

I tried second approach and it is working. Added tar and procps in core-tools packagegroup.

**Comment by avinash-palleti** [comment]
@lucasdemarchi I have submitted pull request to update tar and ps utilities. Now from the excel sheet i attached above, we need to decide which tools has to be updated.

**Comment by lucasdemarchi** [comment]
@avinash-palleti thanks.

Put the table here in plain text so it's easier to comment on them rather than using a spreadsheet

**Comment by avinash-palleti** [comment]
Utilities from busybox:

addgroup
adduser
ash
blkid
clear
cpio
delgroup
deluser
dnsdomainname
dumpkmap
dumpleases
free
fsck
fuser
getopt
getty
gunzip
gzip
hostname
hwclock
ifconfig
ifdown
ifup
ip
killall
klogd
less
loadfont
loadkmap
logread
microcom
nc
netstat
nslookup
patch
ping
ping6
ps
rdate
reset
resize
route
run-parts
setconsole
start-stop-daemon
sysctl
syslogd
tar
telnet
tftp
time
top
traceroute
udhcpc
udhcpd
unzip
usleep
vi
vlock
watch
wget
which
zcat

**Comment by lucasdemarchi** [comment]
@avinash-palleti thanks for the list. I think the one to move right now is `top`. The others can remain as is for now.

**Comment by avinash-palleti** [comment]
@lucasdemarchi "top" utility is also from procps-ng
Above patch should include "top" utility also, will confirm tomorrow after checking on final image.

**Comment by avinash-palleti** [comment]
@lucasdemarchi 
Following utilities are already from procps-ng after merging above patch,
free
ps
sysctl
top
watch

**Comment by lucasdemarchi** [comment]
Thanks
