### ISSUE TITLE
how to install nano editor

### ISSUE THREAD

**Issue by blankered** [intel-aero/meta-intel-aero#66]
While it isn't crucial that I use nano, I wanted to install it as apart of the process of learning to use Yocto. I thought it might be good to post this problem here so others who are looking to develop with Yocto might learn as well. 

Following forum advice for the Intel Edision, I attempted to install nano using the following command:

wget http://www.nano-editor.org/dist/v2.2/nano-2.2.6.tar.gz && tar xvf nano-2.2.6.tar.gz && cd nano-2.2.6 && ./configure && make && make install 

which spits out:

Connecting to www.nano-editor.org (213.138.109.86:80)
Connecting to www.nano-editor.org (213.138.109.86:443)
wget: bad header line: protocol mismatch.

How do I fix this issue? I tried using opkg and smart but they don't have an package sources....

**Comment by lucasdemarchi** [comment]
> wget http://www.nano-editor.org/dist/v2.2/nano-2.2.6.tar.gz && tar xvf nano-2.2.6.tar.gz && cd nano-2.2.6 && ./configure && make && make install
> 
> which spits out:
> 
> Connecting to www.nano-editor.org (213.138.109.86:80)
> Connecting to www.nano-editor.org (213.138.109.86:443)
> wget: bad header line: protocol mismatch.

You are telling wget to download nano, but your board is not connected to the internet.

If you are building your own BSP, you should rather add it to the packages to be installed in the yocto recipes. See yocto manual for that.

**Comment by blankered** [comment]
Thanks for your help!
