### ISSUE TITLE
Remove or shorten 10 seconds boot delay if there is only one image available

### ISSUE THREAD

**Issue by LorenzMeier** [intel-aero/meta-intel-aero#7]
The 10 seconds delay is pretty annoying for on-vehicle use and as the boot prompt has only one choice its not adding any value. If the recovery console is significant then it should be cut to 2-3 seconds.

**Comment by intel-aero** [comment]
Lorenz - We will resolve this in next release, which is due shortly. Thank you!

**Comment by intel-aero** [comment]
This issue is resolved in release v01.00.02
