### ISSUE TITLE
Wiki error: "How to get to a console" incorrect.

### ISSUE THREAD

**Issue by JochiPochi** [intel-aero/meta-intel-aero#75]
This one is an easy one:

On the Getting started wiki:
https://github.com/intel-aero/meta-intel-aero/wiki/Quickstart-Guide#via-uarts1
The description of UART 1 on the power cable is backwards, it says:
- Following is the pin configuration of UART(s1) located on the power connector cable: Black is ground, Blue is TX and Yellow is RX. Connect the USB-TTL serial cable to your host and other end of cable(i.e TTL) to UART breakout with correct mapping of GND,TX and RX.

It should say:

Black is ground, Blue is RX and Yellow is TX. 

Or:

Black is ground, Blue should be connected to the USB-to-TTL TX and Yellow to the USB-to-TTL RX.

**Comment by zehortigoza** [comment]
Thanks, fixed.
