### ISSUE TITLE
WIFI SSID not showing up on latest image

### ISSUE THREAD

**Issue by LorenzMeier** [intel-aero/meta-intel-aero#8]
I'm not getting the hostap / SSID being broadcasted. I have the image from Tue Aug 16, built 15:11:54. I checked the known limitations but that did neither fix it nor is it practical to do this in the field. Reliable wifi is critical to make operating the board feasible.

**Comment by intel-aero** [comment]
Lorenz - We can have captured this as a know issue and we will resolve this in next release, which is due shortly. Thank you!

**Comment by intel-aero** [comment]
This issue is resolved in release v01.00.02
