### ISSUE TITLE
Including 32-bit multilib configuration for jam-stapl breaks numerous recipes in meta-ros

### ISSUE THREAD

**Issue by JochiPochi** [intel-aero/meta-intel-aero#9]
Several recipes for ROS packages from the Yocto layer https://github.com/bmwcarit/meta-ros experience packaging issues of the following kind: 

`
ERROR: genmsg-0.5.7-r0 do_package: QA Issue: genmsg: Files/directories were installed but not shipped in any package:
`
`
ERROR: roscpp-traits-0.5.7-r0 do_package: Fatal QA errors found, failing task.
`
`
ERROR: roscpp-traits-0.5.7-r0 do_package: Function failed: do_package
`
`
ERROR: genmsg-0.5.7-r0 do_package: Fatal QA errors found, failing task.
`
`
ERROR: genmsg-0.5.7-r0 do_package: Function failed: do_package
`
`
ERROR: roscpp-traits-0.5.7-r0 do_package: QA Issue: roscpp-traits: Files/directories were installed but not shipped in any package:
`
`
roscpp-traits: 3 installed and not shipped files. [installed-vs-shipped]
`

I have isolated the issue to come from https://github.com/intel-aero/meta-intel-aero/commit/f2374a86abe055d1b3cadf91ecbb7c40f1a8c275, specifically the additions to the `conf/local.conf` file to support a 32-bit arch cross-compilation scheme: https://github.com/intel-aero/meta-intel-aero/commit/f2374a86abe055d1b3cadf91ecbb7c40f1a8c275#diff-f95cc75ba253227ffb1e5b0c0705be2fR242

This prevents the a successful inclusion of ROS for the intel-aero platform.

**Comment by intel-aero** [comment]
We are aware of this issue and it will be addressed in next release, which is due soon.

**Comment by JochiPochi** [comment]
Thanks!, I'll be looking forward to it.
What would you suggest to do on the mean time? 
Is it okay to remove the entire commit? (https://github.com/intel-aero/meta-intel-aero/commit/f2374a86abe055d1b3cadf91ecbb7c40f1a8c275)

**Comment by omarrmz** [comment]
Hi, the jam binary is compiled statically anyway, these were wrongly kept from an alternate recipe that used actual sources, they are not needed. You can remove the following from the conf and if possible submit a patch (we have a patch to be included at the next release but will drop it if you submit one):

+require conf/multilib.conf
+MULTILIBS = "multilib:lib32"
+DEFAULTTUNE_virtclass-multilib-lib32 = "x86"

**Comment by JochiPochi** [comment]
Awesome. I'll work on something, test and PR if it works well then. Thanks

**Comment by intel-aero** [comment]
This issue is resolved in release v01.00.02

**Comment by JochiPochi** [comment]
Thank you!
