### ISSUE TITLE
Update Yocto to 2.1.2

### ISSUE THREAD

**Issue by whbruce** [intel-aero/meta-intel-aero#91]
Current OS is built by Yocto 2.1.1. Recommend move to 2.1.2 to get ~200 bug fixes and CVEs. Kernel moves to 4.4.26 but package versions remain the same so user space ABI is unchanged. This should just require changes in repo manifest to contain appropriate poky and meta-openembedded revisions.

**Comment by lucasdemarchi** [comment]
This can be done. I think I have the kernel patches rebased which would be the major limitation.

**Comment by whbruce** [comment]
Good point on kernel patches. The following didn't apply. 
```
0003-dma-dw-must-initialize-dma-channel.patch 
0012-pmic-intel-port-whiskey-cove-driver.patch 
0019-regulator-whiskey_cove-implements-WhiskeyCove-pmic-V.patch 
0020-pmic-whiskeycove-add-vqmmc-regulator-for-SD-host-vol.patch 
```
I'll update to 2.1.2 but leave kernel at 4.4.3 for the time being.

**Comment by whbruce** [comment]
Done. See manifest [PR #4](https://github.com/intel-aero/intel-aero-manifest/pull/8)
