### ISSUE TITLE
SFTP not working

### ISSUE THREAD

**Issue by mindThomas** [intel-aero/meta-intel-aero#95]
It is not possible to connect to the drone over SFTP. Only SCP file transfers over SSH is working.
SFTP is tested with both Nautilus and Filezilla.

The OpenSSH config on the drone, located within "/etc/ssh/sshd_config" shows that the sftp server is enabled:
`Subsystem	sftp	/usr/libexec/sftp-server`
Though this binary is nowhere to be found within the drone.

Actually the only parts related to sftp on the drone is as an avahi service, just publishing the sftp service as available even though it is not.

**Comment by lucasdemarchi** [comment]
Thanks. I'll take a look on what's needed to enable it.

**Comment by whbruce** [comment]
Try `openssh-sftp-server`

**Comment by mindThomas** [comment]
@whbruce The command is not found (not included within the Yocto build)
```
root@intel-aero:~/realsense-examples# openssh-sftp-server
-sh: openssh-sftp-server: command not found
```

**Comment by whbruce** [comment]
Sorry, I meant that you should add this package to the Yocto build
`CORE_IMAGE_EXTRA_INSTALL += "openssh-sftp-server"`

**Comment by lucasdemarchi** [comment]
@whbruce yep, adding it.
